const AUTHENTICATE = "AUTHENTICATE"

const LOGOUT = "LOGOUT"

const UPDATE_PROFILE="UPDATE_PROFILE"

const FETCH_PROVINCE = "FETCH_PROVINCE"

const FETCH_BUSINESS = "FETCH_BUSINESS"

export  {AUTHENTICATE, LOGOUT, UPDATE_PROFILE, FETCH_PROVINCE, FETCH_BUSINESS }