const AUTHENTICATE = "AUTHENTICATE"

const LOGOUT = "LOGOUT"

const UPDATE_PROFILE="UPDATE_PROFILE"

const FETCH_PROVINCE = "FETCH_PROVINCE"

const PUSH_BUSINESS_TO_MODAL = "PUSH_BUSINESS_TO_MODAL"

export  {AUTHENTICATE, LOGOUT, UPDATE_PROFILE, FETCH_PROVINCE, PUSH_BUSINESS_TO_MODAL }